# Generated by Django 4.2.3 on 2023-07-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WaterdipApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktable',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
